### ISSUE TITLE
모달 제작

### ISSUE THREAD

**Issue by devpang20** [code-flash-card/code-flash-card#13]
## 작업 내역
서비스 내에서 사용되는 모달 컴포넌트 제작

## TODO
- [x] 협업 환경 설정
- [x] 모달 컴포넌트 생성
- [x] 모달 컴포넌트 완성
- [x] 모달 컴포넌트 페이지에 붙이기
